name: PHPCS
on: [push]
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPCS check
        uses: MilesChou/php-tools-action/phpcs@master
        with:
          args: index.php
      - name: PHPMD check
        uses: MilesChou/php-tools-action/5.6/phpmd@master
        with:
          args: index.php
      - name: PHPMD check
        uses: MilesChou/php-tools-action/5.6/phpmetrics@master
        with:
          args: index.php
        
